const ActionsTypes = {

  NEWS_REQUESTED: 'NEWS_REQUESTED',
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWS_REJECTED: 'NEWS_REJECTED',

  REGISTRATION_REQUESTED: 'REGISTRATION_REQUESTED',
  REGISTRATION_RECEIVED: 'REGISTRATION_RECEIVED',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',

  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_RECEIVED: 'LOGIN_RECEIVED',
  LOGIN_REJECTED: 'LOGIN_REJECTED',

  LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
  LOGOUT_RECEIVED: 'LOGOUT_RECEIVED',
  LOGOUT_REJECTED: 'LOGOUT_REJECTED',

  AUTHBYTOKEN_REQUESTED: 'AUTHBYTOKEN_REQUESTED',

  GETUSERPAGE_REQUESTED: 'GETUSERPAGE_REQUESTED',
  GETUSERPAGE_RECEIVED: 'GETUSERPAGE_RECEIVED',
  GETUSERPAGE_REJECTED: 'GETUSERPAGE_REJECTED',

  USERPOSTS_REQUESTED: 'USERPOSTS_REQUESTED',
  USERPOSTS_RECEIVED: 'USERPOSTS_RECEIVED',
  USERPOSTS_REJECTED: 'USERPOSTS_REJECTED',
};

export default ActionsTypes;
